In [1]:
# Classification

In [1]:
### import the required packages

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
### load the dataset

In [4]:
df = pd.read_csv("C:\\Users\\sainya.vishwakarma\\Python\\Naive bayes\\hearing_test.csv")
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

In [5]:
### exploratory data analysis

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

In [7]:
### get the statistical info of data

In [8]:
df.describe()

               age  physical_score  test_result
count  5000.000000     5000.000000  5000.000000
mean     51.609000       32.760260     0.600000
std      11.287001        8.169802     0.489947
min      18.000000       -0.000000     0.000000
25%      43.000000       26.700000     0.000000
50%      51.000000       35.300000     1.000000
75%      60.000000       38.900000     1.000000
max      90.000000       50.000000     1.000000

In [9]:
df.isna().sum()

age               0
physical_score    0
test_result       0
dtype: int64

In [10]:
### correlation analysis

In [11]:
df.corr()

                     age  physical_score  test_result
age             1.000000       -0.782146    -0.683171
physical_score -0.782146        1.000000     0.792716
test_result    -0.683171        0.792716     1.000000

In [13]:
### check if dataset is balanced

In [13]:
df['test_result'].value_counts()

test_result
1    3000
0    2000
Name: count, dtype: int64

In [13]:
### data preparation

In [14]:
### split the data into x and y

In [15]:
x = df.drop('test_result',axis=1)
y=df['test_result']

In [16]:
### oversample the dataset using SMOTE

In [17]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_new,y_new=smote.fit_resample(x,y)

In [18]:
### split the data into train and test dataset

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_new,y_new,train_size=0.8,random_state=42)

In [20]:
### build the models

In [21]:
from sklearn.linear_model import LogisticRegressionCV

def build_logistic_regression_model():
    # create the model
    model = LogisticRegressionCV()

    # fit the model
    model.fit(x_train,y_train)

    return model

In [22]:
from sklearn.naive_bayes import GaussianNB 

def build_naive_bayes_model():
    # create the model
    model = GaussianNB()

    # fit the model
    model.fit(x_train,y_train)

    return model

In [23]:
### evaluate models

In [24]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,roc_auc_score,roc_curve,log_loss

def evaluate_model(model_name,model,x,y):
    # predict x
    y_pred = model.predict(x)

    # calculate metrics
    accuracy = accuracy_score(y,y_pred)
    precision = precision_score(y,y_pred)
    recall = recall_score(y,y_pred)
    f1 = f1_score(y,y_pred)
    log= log_loss(y,y_pred)
    roc = roc_auc_score(y,y_pred)

    return model_name,accuracy,precision,recall,f1,log,roc

In [25]:
# create all the  models
model_logistic_regression =  build_logistic_regression_model()
model_naive_bayes_regression = build_naive_bayes_model()

# create an array of models

models = [
    {"model_name": "Logistic Regression", "model":model_logistic_regression },
    {"model_name": "Naive Bayes", "model":model_naive_bayes_regression }
]

C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2137: FutureWarning: The default value of the parameter 'scoring' will change from None, i.e. accuracy, to 'neg_log_loss' in version 1.11. To silence this warning, explicitly set the scoring parameter: scoring='neg_log_loss' for the new, scoring='accuracy' or scoring=None for the old default.
  warnings.warn(
C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

In [26]:
# evaluate all the models on train set

evaluate_metrics=[]

for model_info in models:
    evaluate_metrics.append(evaluate_model(model_info['model_name'],model_info['model'],x_train,y_train))

pd.DataFrame(evaluate_metrics,columns=['model_name','accuracy','precision','recall','f1_score','log_loss','roc_auc_score'])

,model_name,accuracy,precision,recall,f1_score,log_loss,roc_auc_score
0,Logistic Regression,0.912500,0.900646,0.927621,0.913934,3.153820,0.912475
1,Naive Bayes,0.908542,0.898904,0.920965,0.909801,3.296492,0.908521

In [27]:
# evaluate all the models on test set

evaluate_metrics=[]

for model_info in models:
    evaluate_metrics.append(evaluate_model(model_info['model_name'],model_info['model'],x_test,y_test))

pd.DataFrame(evaluate_metrics,columns=['model_name','accuracy','precision','recall','f1_score','log_loss','roc_auc_score'])

,model_name,accuracy,precision,recall,f1_score,log_loss,roc_auc_score
0,Logistic Regression,0.886667,0.884615,0.887584,0.886097,4.084947,0.886673
1,Naive Bayes,0.891667,0.893581,0.887584,0.890572,3.904729,0.891640