### Stacking

## import required packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## load the dataset

In [2]:
df = pd.read_csv("C:\\Users\\sainya.vishwakarma\\Python\\Ensemble Learning\\hearing_test.csv")
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

### exploratory data analysis

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

### find the correlation analysis

In [4]:
df.corr()

                     age  physical_score  test_result
age             1.000000       -0.782146    -0.683171
physical_score -0.782146        1.000000     0.792716
test_result    -0.683171        0.792716     1.000000

### split the dataset into x and y

In [5]:
x = df.drop('test_result',axis=1)
y=df['test_result']

### split the data into train and test dataset

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

### train the models

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

# create the list of base models
base_models=[
    ('knn',KNeighborsClassifier(n_neighbors=3)),
    ('svc',SVC(C=10,kernel='rbf')),
    ('dt',DecisionTreeClassifier(max_depth=3)),
    ('nb',GaussianNB())
]

In [9]:
from sklearn.linear_model import LogisticRegressionCV

meta_model = LogisticRegressionCV(max_iter=1000)

In [11]:
from sklearn.ensemble import StackingClassifier

stacking_classifier =StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

In [12]:
# train the meta model
stacking_classifier.fit(x_train,y_train)

C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2137: FutureWarning: The default value of the parameter 'scoring' will change from None, i.e. accuracy, to 'neg_log_loss' in version 1.11. To silence this warning, explicitly set the scoring parameter: scoring='neg_log_loss' for the new, scoring='accuracy' or scoring=None for the old default.
  warnings.warn(
C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

StackingClassifier(cv=5,
                   estimators=[('knn', KNeighborsClassifier(n_neighbors=3)),
                               ('svc', SVC(C=10)),
                               ('dt', DecisionTreeClassifier(max_depth=3)),
                               ('nb', GaussianNB())],
                   final_estimator=LogisticRegressionCV(max_iter=1000))