### Boosting Algorithm

In [28]:
!pip install xgboost LightGBM catboost

Requirement already satisfied: xgboost in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.3.0)
Requirement already satisfied: LightGBM in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (4.6.0)
Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (1.17.1)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from catboost) (3.10.9)
Requirement already satisfied: pandas<4.0,>=0.24 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from catboost) (3.0.3)
Collecting plotly (from catboost)
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\sainya.vishwakarma\AppData\Local\Programs\Python\Python314\Lib\site-packages (from plotly->catboost) (2.22.1)
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.8/101.7 MB 5.9 MB/s eta 0:00:17
    --------------------------------------- 2.1/101.7 MB 5.9 MB/s eta 0:00:17
   - -------------------------------------- 3.4/101.7 MB 6.6 MB/s eta 0:00:16
   - -------------------------------------- 4.7/101.7 MB 6.3 MB/s eta 0:00:16
   -- ------------------------------------- 5.5/101.7 MB 5.6 MB/s eta 0:00:18
   -- ------------------------------------- 6.0/101.7 MB 5.2 MB/s eta 0:00:19
   -- ------------------------------------- 6.6/101.7 MB 4.9 MB/s eta 0:00:20
   -- ------------------------------------- 7.3/101.7 MB 4.6 MB/s eta 0:00:21
   --- ------------------------------------ 7.9/101.7 MB 4.4 MB/s eta 0:00:22
   --- ------------------------------------ 8.7/101.7 MB 4.3 MB/s eta 0:00:22
   --- ------------------------------------ 9.4/101.7 MB 4.3 MB/s eta 0:00:22
   ---- ----------------------------------- 10.2/101.7 MB 4.2 MB/s eta 0:00:22
   ---- ----------------------------------- 10.7/101.7 MB 4.1 MB/s eta 0:00:23
   ---- ----------------------------------- 11.5/101.7 MB 4.1 MB/s eta 0:00:23
   ---- ----------------------------------- 12.3/101.7 MB 4.0 MB/s eta 0:00:23
   ----- ---------------------------------- 12.8/101.7 MB 4.0 MB/s eta 0:00:23
   ----- ---------------------------------- 13.6/101.7 MB 4.0 MB/s eta 0:00:23
   ----- ---------------------------------- 14.4/101.7 MB 3.9 MB/s eta 0:00:23
   ----- ---------------------------------- 15.2/101.7 MB 3.9 MB/s eta 0:00:23
   ------ --------------------------------- 16.0/101.7 MB 3.9 MB/s eta 0:00:22
   ------ --------------------------------- 16.8/101.7 MB 3.9 MB/s eta 0:00:22
   ------ --------------------------------- 17.6/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 18.4/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 19.1/101.7 MB 3.9 MB/s eta 0:00:22
   ------- -------------------------------- 19.9/101.7 MB 3.9 MB/s eta 0:00:22
   -------- ------------------------------- 20.7/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 21.8/101.7 MB 3.9 MB/s eta 0:00:21
   -------- ------------------------------- 22.5/101.7 MB 3.9 MB/s eta 0:00:21
   --------- ------------------------------ 23.3/101.7 MB 3.9 MB/s eta 0:00:21
   --------- ------------------------------ 24.4/101.7 MB 3.9 MB/s eta 0:00:20
   --------- ------------------------------ 25.2/101.7 MB 3.9 MB/s eta 0:00:20
   ---------- ----------------------------- 26.0/101.7 MB 3.9 MB/s eta 0:00:20
   ---------- ----------------------------- 27.0/101.7 MB 4.0 MB/s eta 0:00:19
   ---------- ----------------------------- 27.8/101.7 MB 4.0 MB/s eta 0:00:19
   ----------- ---------------------------- 28.8/101.7 MB 4.0 MB/s eta 0:00:19
   ----------- ---------------------------- 29.9/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 30.7/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 31.7/101.7 MB 4.0 MB/s eta 0:00:18
   ------------ --------------------------- 32.8/101.7 MB 4.0 MB/s eta 0:00:18
   ------------- -------------------------- 33.6/101.7 MB 4.1 MB/s eta 0:00:17
   ------------- -------------------------- 34.6/101.7 MB 4.1 MB/s eta 0:00:17
   -------------- ------------------------- 35.7/101.7 MB 4.1 MB/s eta 0:00:17
   -------------- ------------------------- 36.7/101.7 MB 4.1 MB/s eta 0:00:16
   -------------- ------------------------- 37.5/101.7 MB 4.1 MB/s eta 0:00:16
   --------------- ------------------------ 38.5/101.7 MB 4.1 MB/s eta 0:00:16
   --------------- ------------------------ 39.6/101.7 MB 4.2 MB/s eta 0:00:15
   --------------- ------------------------ 40.6/101.7 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 41.7/101.7 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 42.7/101.7 MB 4.2 MB/s eta 0:00:15
   ----------------- ---------------------- 43.8/101.7 MB 4.2 MB/s eta 0:00:14
   ----------------- ---------------------- 45.1/101.7 MB 4.3 MB/s eta 0:00:14
   ------------------ --------------------- 46.1/101.7 MB 4.3 MB/s eta 0:00:14
   ------------------ --------------------- 47.4/101.7 MB 4.3 MB/s eta 0:00:13
   ------------------- -------------------- 48.8/101.7 MB 4.3 MB/s eta 0:00:13
   ------------------- -------------------- 50.1/101.7 MB 4.4 MB/s eta 0:00:12
   ------------------- -------------------- 50.9/101.7 MB 4.4 MB/s eta 0:00:12
   -------------------- ------------------- 51.6/101.7 MB 4.4 MB/s eta 0:00:12
   -------------------- ------------------- 52.4/101.7 MB 4.3 MB/s eta 0:00:12
   -------------------- ------------------- 53.0/101.7 MB 4.3 MB/s eta 0:00:12
   --------------------- ------------------ 53.7/101.7 MB 4.3 MB/s eta 0:00:12
   --------------------- ------------------ 54.5/101.7 MB 4.3 MB/s eta 0:00:12
   --------------------- ------------------ 55.3/101.7 MB 4.3 MB/s eta 0:00:11
   ---------------------- ----------------- 56.1/101.7 MB 4.3 MB/s eta 0:00:11
   ---------------------- ----------------- 56.9/101.7 MB 4.3 MB/s eta 0:00:11
   ---------------------- ----------------- 57.4/101.7 MB 4.3 MB/s eta 0:00:11
   ---------------------- ----------------- 58.5/101.7 MB 4.2 MB/s eta 0:00:11
   ----------------------- ---------------- 59.2/101.7 MB 4.2 MB/s eta 0:00:11
   ----------------------- ---------------- 59.8/101.7 MB 4.2 MB/s eta 0:00:10
   ----------------------- ---------------- 60.6/101.7 MB 4.2 MB/s eta 0:00:10
   ------------------------ --------------- 61.3/101.7 MB 4.2 MB/s eta 0:00:10
   ------------------------ --------------- 62.4/101.7 MB 4.2 MB/s eta 0:00:10
   ------------------------ --------------- 63.2/101.7 MB 4.2 MB/s eta 0:00:10
   ------------------------- -------------- 64.0/101.7 MB 4.2 MB/s eta 0:00:10
   ------------------------- -------------- 64.7/101.7 MB 4.2 MB/s eta 0:00:09
   ------------------------- -------------- 65.5/101.7 MB 4.2 MB/s eta 0:00:09
   -------------------------- ------------- 66.3/101.7 MB 4.2 MB/s eta 0:00:09
   -------------------------- ------------- 67.1/101.7 MB 4.2 MB/s eta 0:00:09
   -------------------------- ------------- 68.2/101.7 MB 4.2 MB/s eta 0:00:09
   --------------------------- ------------ 68.9/101.7 MB 4.2 MB/s eta 0:00:08
   --------------------------- ------------ 69.7/101.7 MB 4.2 MB/s eta 0:00:08
   --------------------------- ------------ 70.5/101.7 MB 4.2 MB/s eta 0:00:08
   --------------------------- ------------ 71.0/101.7 MB 4.2 MB/s eta 0:00:08
   ---------------------------- ----------- 71.8/101.7 MB 4.1 MB/s eta 0:00:08
   ---------------------------- ----------- 72.4/101.7 MB 4.1 MB/s eta 0:00:08
   ---------------------------- ----------- 73.1/101.7 MB 4.1 MB/s eta 0:00:07
   ----------------------------- ---------- 73.9/101.7 MB 4.1 MB/s eta 0:00:07
   ----------------------------- ---------- 74.7/101.7 MB 4.1 MB/s eta 0:00:07
   ----------------------------- ---------- 75.5/101.7 MB 4.1 MB/s eta 0:00:07
   ----------------------------- ---------- 76.3/101.7 MB 4.1 MB/s eta 0:00:07
   ------------------------------ --------- 77.1/101.7 MB 4.1 MB/s eta 0:00:07
   ------------------------------ --------- 78.1/101.7 MB 4.1 MB/s eta 0:00:06
   ------------------------------- -------- 78.9/101.7 MB 4.1 MB/s eta 0:00:06
   ------------------------------- -------- 79.7/101.7 MB 4.1 MB/s eta 0:00:06
   ------------------------------- -------- 80.5/101.7 MB 4.1 MB/s eta 0:00:06
   -------------------------------- ------- 81.5/101.7 MB 4.1 MB/s eta 0:00:05
   -------------------------------- ------- 82.3/101.7 MB 4.1 MB/s eta 0:00:05
   -------------------------------- ------- 83.4/101.7 MB 4.1 MB/s eta 0:00:05
   --------------------------------- ------ 84.1/101.7 MB 4.1 MB/s eta 0:00:05
   --------------------------------- ------ 85.2/101.7 MB 4.1 MB/s eta 0:00:05
   --------------------------------- ------ 86.0/101.7 MB 4.1 MB/s eta 0:00:04
   ---------------------------------- ----- 86.8/101.7 MB 4.1 MB/s eta 0:00:04
   ---------------------------------- ----- 87.8/101.7 MB 4.1 MB/s eta 0:00:04
   ---------------------------------- ----- 88.6/101.7 MB 4.1 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/101.7 MB 4.1 MB/s eta 0:00:04
   ----------------------------------- ---- 90.4/101.7 MB 4.1 MB/s eta 0:00:03
   ----------------------------------- ---- 91.5/101.7 MB 4.1 MB/s eta 0:00:03
   ------------------------------------ --- 92.3/101.7 MB 4.1 MB/s eta 0:00:03
   ------------------------------------ --- 93.3/101.7 MB 4.1 MB/s eta 0:00:03
   ------------------------------------ --- 94.1/101.7 MB 4.1 MB/s eta 0:00:02
   ------------------------------------- -- 95.2/101.7 MB 4.1 MB/s eta 0:00:02
   ------------------------------------- -- 96.2/101.7 MB 4.1 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 4.1 MB/s eta 0:00:02
   -------------------------------------- - 98.0/101.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  100.1/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 4.0 MB/s  0:00:25
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 4.6 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.9 MB 4.5 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.9 MB 4.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 4.8 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 4.9 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 4.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.7 MB/s  0:00:02
Installing collected packages: plotly, graphviz, catboost

   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## problem statement
- predict the customer's segment based on wine they purchased
- customer_segment will be the dependent variable

## import required packages

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## load the dataset

In [5]:
df = pd.read_csv("C:\\Users\\sainya.vishwakarma\\Python\\Ensemble Learning\\Wine.csv")
df

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

### exploratory data analysis

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64
 13  Customer_Segment      178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

### find the correlation analysis

In [11]:
df.corr()['Customer_Segment'].abs().sort_values()

Alcohol                 0.328222
Malic_Acid              0.437776
Nonflavanoid_Phenols    0.489109
Proanthocyanins         0.499130
Ash_Alcanity            0.517859
Hue                     0.617369
Proline                 0.633717
Total_Phenols           0.719163
OD280                   0.788230
Flavanoids              0.847498
Customer_Segment        1.000000
Name: Customer_Segment, dtype: float64

In [10]:
# drop ash,magnesium and color_intensity
df.drop(['Ash','Magnesium','Color_Intensity'],axis=1,inplace=True)

In [12]:
# check if the dataset is balanced
df['Customer_Segment'].value_counts()

Customer_Segment
2    71
1    59
3    48
Name: count, dtype: int64

### split the dataset into x and y

In [13]:
x = df.drop('Customer_Segment',axis=1)
y=df['Customer_Segment']

In [41]:
# change y
y_new=y-1

In [42]:
y_new

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: Customer_Segment, Length: 178, dtype: int64

### split the data into train and test dataset

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y_new,train_size=0.7,random_state=42)

### train the models

In [44]:
from sklearn.ensemble import AdaBoostClassifier

def create_ada_boost_model():
    model = AdaBoostClassifier()
    model.fit(x_train,y_train) 
    return model

In [45]:
from sklearn.ensemble import GradientBoostingClassifier

def create_gb_boost_model():
    model = GradientBoostingClassifier(learning_rate=0.1,max_depth=4,n_estimators=10,verbose=1)
    model.fit(x_train,y_train) 
    return model

In [46]:
from xgboost import XGBClassifier

def create_xgb_model():
    model = XGBClassifier()
    model.fit(x_train,y_train) 
    return model

In [47]:
from lightgbm import LGBMClassifier

def create_lgbm_model():
    model = LGBMClassifier(learning_rate=0.1,n_estimators=10)
    model.fit(x_train,y_train) 
    return model

In [48]:
from catboost import CatBoostClassifier

def create_catboost_model():
    model = CatBoostClassifier()
    model.fit(x_train,y_train) 
    return model

In [55]:
# evaluate the models
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

def evaluate_model(model,name,x,y):
    y_pred = model.predict(x)
    accuracy = accuracy_score(y,y_pred)
    precision = precision_score(y,y_pred,average='micro')
    recall = recall_score(y,y_pred,average='micro')
    f1 = f1_score(y,y_pred,average='micro')
    return name,accuracy,precision,recall,f1

In [56]:
# create the models

model_ada_boost=create_ada_boost_model()
model_gb=create_gb_boost_model()
model_xgb=create_xgb_model()
model_lgbm=create_lgbm_model()
model_catboot=create_catboost_model()

      Iter       Train Loss   Remaining Time
         1           0.8963            0.07s
         2           0.7535            0.06s
         3           0.6395            0.05s
         4           0.5437            0.04s
         5           0.4646            0.04s
         6           0.3985            0.03s
         7           0.3430            0.02s
         8           0.2959            0.01s
         9           0.2558            0.01s
        10           0.2216            0.00s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000081 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 353
[LightGBM] [Info] Number of data points in the train set: 124, number of used features: 10
[LightGBM] [Info] Start training from score -1.131402
[LightGBM] [Info] Start training from score -0.908259
[LightGBM] [Info] Start training from score -1.293921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Learning rate set to 0.071136
0:	learn: 1.0389562	total: 2.18ms	remaining: 2.17s
1:	learn: 0.9847747	total: 3.68ms	remaining: 1.84s
2:	learn: 0.9286253	total: 5.09ms	remaining: 1.69s
3:	learn: 0.8852436	total: 7ms	remaining: 1.74s
4:	learn: 0.8353990	total: 8.45ms	remaining: 1.68s
5:	learn: 0.7978601	total: 10ms	remaining: 1.66s
6:	learn: 0.7547053	total: 11.5ms	remaining: 1.63s
7:	learn: 0.7240475	total: 13.1ms	remaining: 1.62s
8:	learn: 0.6994660	total: 14.7ms	remaining: 1.61s
9:	learn: 0.6748218	total: 16.1ms	remaining: 1.59s
10:	learn: 0.6469836	total: 17.5ms	remaining: 1.57s
11:	learn: 0.6241805	total: 18.9ms	remaining: 1.55s
12:	learn: 0.5974119	total: 20.7ms	remaining: 1.57s
13:	learn: 0.5741887	total: 22.2ms	remaining: 1.56s
14:	learn: 0.5563143	total: 23.9ms	remaining: 1.57s
15:	learn: 0.5356108	total: 25.4ms	remaining: 1.56s
16:	learn: 0.5166598	total: 27ms	remaining: 1.56s
17:	learn: 0.4985620	total: 28.7ms	remaining: 1.56s
18:	learn: 0.4831476	total: 30.2ms	remaining: 1.56s
19:	learn: 0.4632679	total: 30.7ms	remaining: 1.5s
20:	learn: 0.4443232	total: 32.2ms	remaining: 1.5s
21:	learn: 0.4283625	total: 34.2ms	remaining: 1.52s
22:	learn: 0.4133013	total: 35.8ms	remaining: 1.52s
23:	learn: 0.3991512	total: 37.3ms	remaining: 1.52s
24:	learn: 0.3870603	total: 39.1ms	remaining: 1.52s
25:	learn: 0.3739902	total: 40.6ms	remaining: 1.52s
26:	learn: 0.3604801	total: 42.2ms	remaining: 1.52s
27:	learn: 0.3488023	total: 43.9ms	remaining: 1.52s
28:	learn: 0.3377672	total: 45.5ms	remaining: 1.52s
29:	learn: 0.3281294	total: 47.1ms	remaining: 1.52s
30:	learn: 0.3191985	total: 49ms	remaining: 1.53s
31:	learn: 0.3081660	total: 50.7ms	remaining: 1.53s
32:	learn: 0.3005622	total: 52.4ms	remaining: 1.53s
33:	learn: 0.2925532	total: 54ms	remaining: 1.53s
34:	learn: 0.2862694	total: 55.6ms	remaining: 1.53s
35:	learn: 0.2790748	total: 57.2ms	remaining: 1.53s
36:	learn: 0.2710228	total: 58.7ms	remaining: 1.53s
37:	learn: 0.2634577	total: 60.2ms	remaining: 1.52s
38:	learn: 0.2560572	total: 61.8ms	remaining: 1.52s
39:	learn: 0.2484497	total: 63.3ms	remaining: 1.52s
40:	learn: 0.2435303	total: 64.9ms	remaining: 1.52s
41:	learn: 0.2383614	total: 66.3ms	remaining: 1.51s
42:	learn: 0.2319889	total: 67.7ms	remaining: 1.51s
43:	learn: 0.2261014	total: 69.1ms	remaining: 1.5s
44:	learn: 0.2199610	total: 70.5ms	remaining: 1.5s
45:	learn: 0.2152405	total: 71.9ms	remaining: 1.49s
46:	learn: 0.2102476	total: 73.3ms	remaining: 1.49s
47:	learn: 0.2061806	total: 74.7ms	remaining: 1.48s
48:	learn: 0.2013445	total: 76.2ms	remaining: 1.48s
49:	learn: 0.1978560	total: 77.6ms	remaining: 1.48s
50:	learn: 0.1937943	total: 79ms	remaining: 1.47s
51:	learn: 0.1899759	total: 80.5ms	remaining: 1.47s
52:	learn: 0.1855662	total: 81.9ms	remaining: 1.46s
53:	learn: 0.1818667	total: 83.3ms	remaining: 1.46s
54:	learn: 0.1789007	total: 84.8ms	remaining: 1.46s
55:	learn: 0.1754578	total: 86.2ms	remaining: 1.45s
56:	learn: 0.1725388	total: 87.6ms	remaining: 1.45s
57:	learn: 0.1698814	total: 89ms	remaining: 1.45s
58:	learn: 0.1671538	total: 90.6ms	remaining: 1.45s
59:	learn: 0.1644457	total: 92.1ms	remaining: 1.44s
60:	learn: 0.1622089	total: 93.5ms	remaining: 1.44s
61:	learn: 0.1588049	total: 95ms	remaining: 1.44s
62:	learn: 0.1559516	total: 96.3ms	remaining: 1.43s
63:	learn: 0.1522484	total: 97.7ms	remaining: 1.43s
64:	learn: 0.1496082	total: 99.2ms	remaining: 1.43s
65:	learn: 0.1477667	total: 101ms	remaining: 1.42s
66:	learn: 0.1447413	total: 102ms	remaining: 1.42s
67:	learn: 0.1421360	total: 104ms	remaining: 1.42s
68:	learn: 0.1398059	total: 105ms	remaining: 1.42s
69:	learn: 0.1376685	total: 107ms	remaining: 1.42s
70:	learn: 0.1348369	total: 108ms	remaining: 1.42s
71:	learn: 0.1326934	total: 110ms	remaining: 1.41s
72:	learn: 0.1309118	total: 111ms	remaining: 1.41s
73:	learn: 0.1286944	total: 112ms	remaining: 1.41s
74:	learn: 0.1269505	total: 114ms	remaining: 1.4s
75:	learn: 0.1252053	total: 115ms	remaining: 1.4s
76:	learn: 0.1225672	total: 117ms	remaining: 1.4s
77:	learn: 0.1202099	total: 118ms	remaining: 1.39s
78:	learn: 0.1187083	total: 120ms	remaining: 1.39s
79:	learn: 0.1162663	total: 121ms	remaining: 1.39s
80:	learn: 0.1143903	total: 123ms	remaining: 1.39s
81:	learn: 0.1120246	total: 124ms	remaining: 1.39s
82:	learn: 0.1105479	total: 125ms	remaining: 1.38s
83:	learn: 0.1080614	total: 127ms	remaining: 1.38s
84:	learn: 0.1062671	total: 128ms	remaining: 1.38s
85:	learn: 0.1048276	total: 129ms	remaining: 1.37s
86:	learn: 0.1030361	total: 131ms	remaining: 1.37s
87:	learn: 0.1018862	total: 132ms	remaining: 1.37s
88:	learn: 0.1000920	total: 134ms	remaining: 1.37s
89:	learn: 0.0989832	total: 136ms	remaining: 1.37s
90:	learn: 0.0976019	total: 137ms	remaining: 1.37s
91:	learn: 0.0961094	total: 139ms	remaining: 1.37s
92:	learn: 0.0949124	total: 140ms	remaining: 1.36s
93:	learn: 0.0937457	total: 141ms	remaining: 1.36s
94:	learn: 0.0919062	total: 143ms	remaining: 1.36s
95:	learn: 0.0902624	total: 144ms	remaining: 1.35s
96:	learn: 0.0888401	total: 145ms	remaining: 1.35s
97:	learn: 0.0877908	total: 147ms	remaining: 1.35s
98:	learn: 0.0860242	total: 149ms	remaining: 1.35s
99:	learn: 0.0847129	total: 150ms	remaining: 1.35s
100:	learn: 0.0835687	total: 152ms	remaining: 1.35s
101:	learn: 0.0824465	total: 153ms	remaining: 1.35s
102:	learn: 0.0812380	total: 154ms	remaining: 1.34s
103:	learn: 0.0800961	total: 156ms	remaining: 1.34s
104:	learn: 0.0790148	total: 157ms	remaining: 1.34s
105:	learn: 0.0780179	total: 159ms	remaining: 1.34s
106:	learn: 0.0768823	total: 160ms	remaining: 1.34s
107:	learn: 0.0759344	total: 162ms	remaining: 1.33s
108:	learn: 0.0749253	total: 163ms	remaining: 1.33s
109:	learn: 0.0740705	total: 165ms	remaining: 1.33s
110:	learn: 0.0731283	total: 166ms	remaining: 1.33s
111:	learn: 0.0721847	total: 167ms	remaining: 1.33s
112:	learn: 0.0711815	total: 169ms	remaining: 1.32s
113:	learn: 0.0704180	total: 170ms	remaining: 1.32s
114:	learn: 0.0694707	total: 172ms	remaining: 1.32s
115:	learn: 0.0682834	total: 173ms	remaining: 1.32s
116:	learn: 0.0676388	total: 174ms	remaining: 1.32s
117:	learn: 0.0668372	total: 177ms	remaining: 1.32s
118:	learn: 0.0659610	total: 178ms	remaining: 1.32s
119:	learn: 0.0653236	total: 179ms	remaining: 1.31s
120:	learn: 0.0644830	total: 181ms	remaining: 1.31s
121:	learn: 0.0637682	total: 182ms	remaining: 1.31s
122:	learn: 0.0633368	total: 184ms	remaining: 1.31s
123:	learn: 0.0626308	total: 185ms	remaining: 1.31s
124:	learn: 0.0620989	total: 186ms	remaining: 1.3s
125:	learn: 0.0614727	total: 188ms	remaining: 1.3s
126:	learn: 0.0608476	total: 190ms	remaining: 1.3s
127:	learn: 0.0602357	total: 191ms	remaining: 1.3s
128:	learn: 0.0597651	total: 193ms	remaining: 1.3s
129:	learn: 0.0591034	total: 194ms	remaining: 1.3s
130:	learn: 0.0586003	total: 196ms	remaining: 1.3s
131:	learn: 0.0578466	total: 198ms	remaining: 1.3s
132:	learn: 0.0572363	total: 199ms	remaining: 1.3s
133:	learn: 0.0567977	total: 201ms	remaining: 1.3s
134:	learn: 0.0560241	total: 202ms	remaining: 1.29s
135:	learn: 0.0553801	total: 204ms	remaining: 1.3s
136:	learn: 0.0549870	total: 206ms	remaining: 1.29s
137:	learn: 0.0543616	total: 207ms	remaining: 1.29s
138:	learn: 0.0537968	total: 209ms	remaining: 1.29s
139:	learn: 0.0534008	total: 210ms	remaining: 1.29s
140:	learn: 0.0528633	total: 211ms	remaining: 1.29s
141:	learn: 0.0525123	total: 213ms	remaining: 1.29s
142:	learn: 0.0519905	total: 215ms	remaining: 1.28s
143:	learn: 0.0514311	total: 216ms	remaining: 1.28s
144:	learn: 0.0508079	total: 218ms	remaining: 1.28s
145:	learn: 0.0503389	total: 220ms	remaining: 1.28s
146:	learn: 0.0499303	total: 221ms	remaining: 1.28s
147:	learn: 0.0495930	total: 223ms	remaining: 1.28s
148:	learn: 0.0489275	total: 224ms	remaining: 1.28s
149:	learn: 0.0484563	total: 225ms	remaining: 1.28s
150:	learn: 0.0479325	total: 227ms	remaining: 1.27s
151:	learn: 0.0476003	total: 228ms	remaining: 1.27s
152:	learn: 0.0470288	total: 230ms	remaining: 1.27s
153:	learn: 0.0464905	total: 231ms	remaining: 1.27s
154:	learn: 0.0460350	total: 233ms	remaining: 1.27s
155:	learn: 0.0456512	total: 234ms	remaining: 1.27s
156:	learn: 0.0452437	total: 236ms	remaining: 1.26s
157:	learn: 0.0449245	total: 237ms	remaining: 1.26s
158:	learn: 0.0445112	total: 238ms	remaining: 1.26s
159:	learn: 0.0441801	total: 240ms	remaining: 1.26s
160:	learn: 0.0438060	total: 241ms	remaining: 1.26s
161:	learn: 0.0434639	total: 243ms	remaining: 1.26s
162:	learn: 0.0431213	total: 244ms	remaining: 1.25s
163:	learn: 0.0428224	total: 246ms	remaining: 1.25s
164:	learn: 0.0425339	total: 247ms	remaining: 1.25s
165:	learn: 0.0422339	total: 249ms	remaining: 1.25s
166:	learn: 0.0418994	total: 250ms	remaining: 1.25s
167:	learn: 0.0416078	total: 251ms	remaining: 1.25s
168:	learn: 0.0412259	total: 253ms	remaining: 1.24s
169:	learn: 0.0409438	total: 254ms	remaining: 1.24s
170:	learn: 0.0406670	total: 256ms	remaining: 1.24s
171:	learn: 0.0403269	total: 257ms	remaining: 1.24s
172:	learn: 0.0401068	total: 258ms	remaining: 1.24s
173:	learn: 0.0398496	total: 260ms	remaining: 1.24s
174:	learn: 0.0394537	total: 262ms	remaining: 1.23s
175:	learn: 0.0390318	total: 263ms	remaining: 1.23s
176:	learn: 0.0388312	total: 265ms	remaining: 1.23s
177:	learn: 0.0385295	total: 266ms	remaining: 1.23s
178:	learn: 0.0382745	total: 267ms	remaining: 1.23s
179:	learn: 0.0378568	total: 269ms	remaining: 1.22s
180:	learn: 0.0376083	total: 270ms	remaining: 1.22s
181:	learn: 0.0372802	total: 271ms	remaining: 1.22s
182:	learn: 0.0370114	total: 273ms	remaining: 1.22s
183:	learn: 0.0366935	total: 274ms	remaining: 1.22s
184:	learn: 0.0363276	total: 276ms	remaining: 1.22s
185:	learn: 0.0360832	total: 277ms	remaining: 1.21s
186:	learn: 0.0358505	total: 279ms	remaining: 1.21s
187:	learn: 0.0356657	total: 280ms	remaining: 1.21s
188:	learn: 0.0354342	total: 281ms	remaining: 1.21s
189:	learn: 0.0351960	total: 283ms	remaining: 1.21s
190:	learn: 0.0349790	total: 284ms	remaining: 1.2s
191:	learn: 0.0346805	total: 285ms	remaining: 1.2s
192:	learn: 0.0344879	total: 287ms	remaining: 1.2s
193:	learn: 0.0341659	total: 289ms	remaining: 1.2s
194:	learn: 0.0339999	total: 290ms	remaining: 1.2s
195:	learn: 0.0337231	total: 291ms	remaining: 1.2s
196:	learn: 0.0336575	total: 293ms	remaining: 1.19s
197:	learn: 0.0333663	total: 294ms	remaining: 1.19s
198:	learn: 0.0331427	total: 296ms	remaining: 1.19s
199:	learn: 0.0329116	total: 297ms	remaining: 1.19s
200:	learn: 0.0326881	total: 298ms	remaining: 1.19s
201:	learn: 0.0324300	total: 300ms	remaining: 1.18s
202:	learn: 0.0322646	total: 301ms	remaining: 1.18s
203:	learn: 0.0320644	total: 303ms	remaining: 1.18s
204:	learn: 0.0318905	total: 304ms	remaining: 1.18s
205:	learn: 0.0316681	total: 306ms	remaining: 1.18s
206:	learn: 0.0314286	total: 307ms	remaining: 1.18s
207:	learn: 0.0312293	total: 308ms	remaining: 1.17s
208:	learn: 0.0310871	total: 310ms	remaining: 1.17s
209:	learn: 0.0309312	total: 311ms	remaining: 1.17s
210:	learn: 0.0307604	total: 313ms	remaining: 1.17s
211:	learn: 0.0304470	total: 314ms	remaining: 1.17s
212:	learn: 0.0302893	total: 315ms	remaining: 1.17s
213:	learn: 0.0300849	total: 317ms	remaining: 1.16s
214:	learn: 0.0298566	total: 318ms	remaining: 1.16s
215:	learn: 0.0296842	total: 320ms	remaining: 1.16s
216:	learn: 0.0295433	total: 321ms	remaining: 1.16s
217:	learn: 0.0292965	total: 322ms	remaining: 1.16s
218:	learn: 0.0291203	total: 324ms	remaining: 1.15s
219:	learn: 0.0289739	total: 325ms	remaining: 1.15s
220:	learn: 0.0288488	total: 326ms	remaining: 1.15s
221:	learn: 0.0286887	total: 328ms	remaining: 1.15s
222:	learn: 0.0285767	total: 329ms	remaining: 1.15s
223:	learn: 0.0284593	total: 331ms	remaining: 1.15s
224:	learn: 0.0282708	total: 332ms	remaining: 1.14s
225:	learn: 0.0281024	total: 334ms	remaining: 1.14s
226:	learn: 0.0279078	total: 335ms	remaining: 1.14s
227:	learn: 0.0276788	total: 337ms	remaining: 1.14s
228:	learn: 0.0274987	total: 338ms	remaining: 1.14s
229:	learn: 0.0273593	total: 339ms	remaining: 1.14s
230:	learn: 0.0271539	total: 341ms	remaining: 1.13s
231:	learn: 0.0270396	total: 342ms	remaining: 1.13s
232:	learn: 0.0269281	total: 344ms	remaining: 1.13s
233:	learn: 0.0267330	total: 346ms	remaining: 1.13s
234:	learn: 0.0265874	total: 347ms	remaining: 1.13s
235:	learn: 0.0264098	total: 349ms	remaining: 1.13s
236:	learn: 0.0263093	total: 350ms	remaining: 1.13s
237:	learn: 0.0261992	total: 351ms	remaining: 1.12s
238:	learn: 0.0260829	total: 353ms	remaining: 1.12s
239:	learn: 0.0259687	total: 354ms	remaining: 1.12s
240:	learn: 0.0257809	total: 355ms	remaining: 1.12s
241:	learn: 0.0256780	total: 357ms	remaining: 1.12s
242:	learn: 0.0255844	total: 359ms	remaining: 1.12s
243:	learn: 0.0254586	total: 360ms	remaining: 1.12s
244:	learn: 0.0253566	total: 362ms	remaining: 1.11s
245:	learn: 0.0252165	total: 363ms	remaining: 1.11s
246:	learn: 0.0250930	total: 365ms	remaining: 1.11s
247:	learn: 0.0249219	total: 366ms	remaining: 1.11s
248:	learn: 0.0247445	total: 367ms	remaining: 1.11s
249:	learn: 0.0246034	total: 369ms	remaining: 1.11s
250:	learn: 0.0244561	total: 370ms	remaining: 1.1s
251:	learn: 0.0243305	total: 372ms	remaining: 1.1s
252:	learn: 0.0241933	total: 373ms	remaining: 1.1s
253:	learn: 0.0241057	total: 375ms	remaining: 1.1s
254:	learn: 0.0239827	total: 376ms	remaining: 1.1s
255:	learn: 0.0238746	total: 377ms	remaining: 1.1s
256:	learn: 0.0237769	total: 379ms	remaining: 1.09s
257:	learn: 0.0236948	total: 381ms	remaining: 1.09s
258:	learn: 0.0235833	total: 382ms	remaining: 1.09s
259:	learn: 0.0234928	total: 383ms	remaining: 1.09s
260:	learn: 0.0234158	total: 385ms	remaining: 1.09s
261:	learn: 0.0232420	total: 386ms	remaining: 1.09s
262:	learn: 0.0230742	total: 388ms	remaining: 1.09s
263:	learn: 0.0229634	total: 390ms	remaining: 1.09s
264:	learn: 0.0228482	total: 391ms	remaining: 1.08s
265:	learn: 0.0227373	total: 393ms	remaining: 1.08s
266:	learn: 0.0226348	total: 394ms	remaining: 1.08s
267:	learn: 0.0225361	total: 396ms	remaining: 1.08s
268:	learn: 0.0223876	total: 397ms	remaining: 1.08s
269:	learn: 0.0222764	total: 398ms	remaining: 1.08s
270:	learn: 0.0221512	total: 400ms	remaining: 1.07s
271:	learn: 0.0220308	total: 402ms	remaining: 1.07s
272:	learn: 0.0219440	total: 403ms	remaining: 1.07s
273:	learn: 0.0218484	total: 405ms	remaining: 1.07s
274:	learn: 0.0217762	total: 406ms	remaining: 1.07s
275:	learn: 0.0216835	total: 407ms	remaining: 1.07s
276:	learn: 0.0215707	total: 409ms	remaining: 1.07s
277:	learn: 0.0214467	total: 410ms	remaining: 1.06s
278:	learn: 0.0213573	total: 412ms	remaining: 1.06s
279:	learn: 0.0212751	total: 413ms	remaining: 1.06s
280:	learn: 0.0211904	total: 414ms	remaining: 1.06s
281:	learn: 0.0211092	total: 416ms	remaining: 1.06s
282:	learn: 0.0210420	total: 417ms	remaining: 1.06s
283:	learn: 0.0209355	total: 419ms	remaining: 1.05s
284:	learn: 0.0208745	total: 420ms	remaining: 1.05s
285:	learn: 0.0207919	total: 421ms	remaining: 1.05s
286:	learn: 0.0207103	total: 423ms	remaining: 1.05s
287:	learn: 0.0206050	total: 424ms	remaining: 1.05s
288:	learn: 0.0204731	total: 426ms	remaining: 1.05s
289:	learn: 0.0203798	total: 427ms	remaining: 1.04s
290:	learn: 0.0202527	total: 429ms	remaining: 1.04s
291:	learn: 0.0201401	total: 430ms	remaining: 1.04s
292:	learn: 0.0200279	total: 432ms	remaining: 1.04s
293:	learn: 0.0199488	total: 433ms	remaining: 1.04s
294:	learn: 0.0198652	total: 434ms	remaining: 1.04s
295:	learn: 0.0197767	total: 436ms	remaining: 1.04s
296:	learn: 0.0196649	total: 437ms	remaining: 1.03s
297:	learn: 0.0195819	total: 438ms	remaining: 1.03s
298:	learn: 0.0195133	total: 440ms	remaining: 1.03s
299:	learn: 0.0194129	total: 441ms	remaining: 1.03s
300:	learn: 0.0193446	total: 442ms	remaining: 1.03s
301:	learn: 0.0192776	total: 444ms	remaining: 1.03s
302:	learn: 0.0191799	total: 446ms	remaining: 1.02s
303:	learn: 0.0191094	total: 447ms	remaining: 1.02s
304:	learn: 0.0190529	total: 449ms	remaining: 1.02s
305:	learn: 0.0189956	total: 450ms	remaining: 1.02s
306:	learn: 0.0189299	total: 452ms	remaining: 1.02s
307:	learn: 0.0188530	total: 453ms	remaining: 1.02s
308:	learn: 0.0187656	total: 455ms	remaining: 1.02s
309:	learn: 0.0186885	total: 456ms	remaining: 1.01s
310:	learn: 0.0186341	total: 457ms	remaining: 1.01s
311:	learn: 0.0185465	total: 459ms	remaining: 1.01s
312:	learn: 0.0184581	total: 460ms	remaining: 1.01s
313:	learn: 0.0183915	total: 462ms	remaining: 1.01s
314:	learn: 0.0183103	total: 463ms	remaining: 1.01s
315:	learn: 0.0182554	total: 465ms	remaining: 1s
316:	learn: 0.0181978	total: 466ms	remaining: 1s
317:	learn: 0.0181468	total: 467ms	remaining: 1s
318:	learn: 0.0180889	total: 469ms	remaining: 1s
319:	learn: 0.0180374	total: 470ms	remaining: 999ms
320:	learn: 0.0179365	total: 471ms	remaining: 997ms
321:	learn: 0.0178501	total: 473ms	remaining: 996ms
322:	learn: 0.0177902	total: 474ms	remaining: 994ms
323:	learn: 0.0177310	total: 476ms	remaining: 993ms

In [57]:
# create list of all models

models=[
    {"name":"Ada Boost","model":model_ada_boost},
    {"name":"Gradient Boost","model":model_gb},
    {"name":"XG Boost","model":model_xgb},
    {"name":"LGBM","model":model_lgbm},
    {"name":"Cat Boost","model":model_catboot},
]

In [59]:
# evaluate all the models on train set

train_metrics=[]
for info in models:
    train_metrics.append(evaluate_model(info['model'],info['name'],x_train,y_train))
pd.DataFrame(train_metrics,columns=['Algorithm','Accuracy','Precision','Recall','F1 Score'])

        Algorithm  Accuracy  Precision    Recall  F1 Score
0       Ada Boost  1.000000   1.000000  1.000000  1.000000
1  Gradient Boost  1.000000   1.000000  1.000000  1.000000
2        XG Boost  1.000000   1.000000  1.000000  1.000000
3            LGBM  0.983871   0.983871  0.983871  0.983871
4       Cat Boost  1.000000   1.000000  1.000000  1.000000

In [60]:
# evaluate all the models on test set

test_metrics=[]
for info in models:
    test_metrics.append(evaluate_model(info['model'],info['name'],x_test,y_test))
pd.DataFrame(test_metrics,columns=['Algorithm','Accuracy','Precision','Recall','F1 Score'])

        Algorithm  Accuracy  Precision    Recall  F1 Score
0       Ada Boost  0.944444   0.944444  0.944444  0.944444
1  Gradient Boost  0.925926   0.925926  0.925926  0.925926
2        XG Boost  0.944444   0.944444  0.944444  0.944444
3            LGBM  0.944444   0.944444  0.944444  0.944444
4       Cat Boost  0.962963   0.962963  0.962963  0.962963